on:
  pull_request:
    types:
      - closed

jobs:
  state_event_type:
    runs-on: ubuntu-latest
    steps:
    - name: if_pr
      if: github.event.pull_request
      run: |
        echo An pull request was closed
        echo "${{github.event.pull_request.number}}"
    - uses: actions/checkout@v3
    - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #ISSUE_URL: ${{ github.event.issue.html_url }}
          -name: Upon Merge Approval Reasign to QA with Label
   
      run: |
          gh issue reopen "${{ github.event.pull_request.number }}"
          gh issue edit "${{ github.event.pull_request.number }}" --remove-assignee "@me"
          gh issue edit "${{ github.event.pull_request.number }}" --remove-label "bug"
          gh issue edit "${{ github.event.pull_request.number }}" --add-label "documentation"
          gh issue edit "${{ github.event.pull_request.number }}" --add-assignee ali-saeed91
