on:
  pull_request:
    types:
      - closed

jobs:
  state_event_type:
    runs-on: ubuntu-latest
    steps:
    - name: if_pr
      if: github.event.pull_request
      run: |
        echo An pull request was closed
        echo "${{github.event.pull_request.number}}"
    - uses: actions/checkout@v3
    - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #ISSUE_URL: ${{ github.event.issue.html_url }}
          -name: Upon Merge Approval Reasign to QA with Label
   
      run: |
          gh pr view "${{github.event.pull_request.number}}" > tmp.txt
          TEMP=$(grep -hnr "#" tmp.txt)
          echo "$TEMP"
          ISSUENO=${TEMP#*#}
          echo "$ISSUENO"
          gh issue reopen "$ISSUENO"
          gh issue edit "$ISSUENO" --remove-assignee "@me"
          gh issue edit "$ISSUENO" --remove-label "bug"
          gh issue edit "$ISSUENO" --add-label "documentation"
          gh issue edit "$ISSUENO" --add-assignee ali-saeed91
          issue-number=$(echo "$ISSUENO" | xargs)
          echo "$issue-number"
